platform :ios, '16.0'

inhibit_all_warnings!

target 'BeThere' do
  use_frameworks!

  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'SwiftLint'
  pod 'SwiftGen'
  pod 'Resolver'

end

target 'BeThereTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end